#create_clock -period 2.500 -name clk_ -waveform {0.000 1.250} [list [get_nets cms_pix_28_fw_top_bd_i/clk_wiz_0/inst/clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0] [get_nets cms_pix_28_fw_top_bd_i/clk_wiz_0/clk_out1]]
#set_input_delay -clock [get_clocks -of_objects [get_pins cms_pix_28_fw_top_bd_i/clk_wiz_0/inst/mmcme4_adv_inst/CLKFBOUT]] -max -add_delay  1.000 [get_ports -filter { NAME =~  "*dnn_out_0_n*" && DIRECTION == "IN" }]
#set_input_delay -clock [get_clocks -of_objects [get_pins cms_pix_28_fw_top_bd_i/clk_wiz_0/inst/mmcme4_adv_inst/CLKFBOUT]] -min -add_delay -1.000 [get_ports -filter { NAME =~  "*dnn_out_0_p*" && DIRECTION == "IN" }]
#set_input_delay -clock [get_clocks -of_objects [get_pins cms_pix_28_fw_top_bd_i/clk_wiz_0/inst/mmcme4_adv_inst/CLKFBOUT]] -max -add_delay  1.000 [get_ports -filter { NAME =~  "*dnn_out_0_p*" && DIRECTION == "IN" }]
#set_input_delay -clock [get_clocks -of_objects [get_pins cms_pix_28_fw_top_bd_i/clk_wiz_0/inst/mmcme4_adv_inst/CLKFBOUT]] -min -add_delay -1.000 [get_ports -filter { NAME =~  "*dnn_out_1_n*" && DIRECTION == "IN" }]
#set_input_delay -clock [get_clocks -of_objects [get_pins cms_pix_28_fw_top_bd_i/clk_wiz_0/inst/mmcme4_adv_inst/CLKFBOUT]] -max -add_delay  1.000 [get_ports -filter { NAME =~  "*dnn_out_1_n*" && DIRECTION == "IN" }]
#set_input_delay -clock [get_clocks -of_objects [get_pins cms_pix_28_fw_top_bd_i/clk_wiz_0/inst/mmcme4_adv_inst/CLKFBOUT]] -min -add_delay -1.000 [get_ports -filter { NAME =~  "*dnn_out_1_p*" && DIRECTION == "IN" }]
#set_input_delay -clock [get_clocks -of_objects [get_pins cms_pix_28_fw_top_bd_i/clk_wiz_0/inst/mmcme4_adv_inst/CLKFBOUT]] -max -add_delay  1.000 [get_ports -filter { NAME =~  "*dnn_out_1_p*" && DIRECTION == "IN" }]

#-min used for HOLD  analysis
#-max used for SETUP analysis
#set_input_delay -clock [get_clocks -of_objects [get_pins cms_pix_28_fw_top_bd_i/clk_wiz_0/inst/mmcme4_adv_inst/CLKOUT0]] -min -add_delay 2.250 [get_ports -filter { NAME =~  "*scan_out_test*" && DIRECTION == "IN" }]
#set_input_delay -clock [get_clocks -of_objects [get_pins cms_pix_28_fw_top_bd_i/clk_wiz_0/inst/mmcme4_adv_inst/CLKOUT0]] -max -add_delay 2.250 [get_ports -filter { NAME =~  "*scan_out_test*" && DIRECTION == "IN" }]


#create_clock -period 5.000 -name VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0 -waveform {0.000 2.500}
#set_input_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0] -min -add_delay 2.500 [get_ports -filter { NAME =~  "*scan_out_test*" && DIRECTION == "IN" }]
#set_input_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0] -max -add_delay 2.500 [get_ports -filter { NAME =~  "*scan_out_test*" && DIRECTION == "IN" }]
#set_input_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0] -min -add_delay 2.500 [get_ports -filter { NAME =~  "*config_out*" && DIRECTION == "IN" }]
#set_input_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0] -max -add_delay 2.500 [get_ports -filter { NAME =~  "*config_out*" && DIRECTION == "IN" }]
#set_input_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0] -min -add_delay 2.500 [get_ports -filter { NAME =~  "*dnn_out*" && DIRECTION == "IN" }]
#set_input_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0] -max -add_delay 2.500 [get_ports -filter { NAME =~  "*dnn_out*" && DIRECTION == "IN" }]
#set_input_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0] -min -add_delay 2.500 [get_ports -filter { NAME =~  "*scan_out*" && DIRECTION == "IN" }]
#set_input_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0] -max -add_delay 2.500 [get_ports -filter { NAME =~  "*scan_out*" && DIRECTION == "IN" }]
#set_input_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0] -min -add_delay 0.100 [get_ports {config_out_n[0]}]
#set_input_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0] -max -add_delay 1.000 [get_ports {config_out_n[0]}]
#set_input_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0] -min -add_delay 0.100 [get_ports {config_out_p[0]}]
#set_input_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0] -max -add_delay 1.000 [get_ports {config_out_p[0]}]
#set_input_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0] -min -add_delay 0.100 [get_ports {dnn_out_0_n[0]}]
#set_input_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0] -max -add_delay 1.000 [get_ports {dnn_out_0_n[0]}]
#set_input_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0] -min -add_delay 0.100 [get_ports {dnn_out_0_p[0]}]
#set_input_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0] -max -add_delay 1.000 [get_ports {dnn_out_0_p[0]}]
#set_input_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0] -min -add_delay 0.100 [get_ports {dnn_out_1_n[0]}]
#set_input_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0] -max -add_delay 1.000 [get_ports {dnn_out_1_n[0]}]
#set_input_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0] -min -add_delay 0.100 [get_ports {dnn_out_1_p[0]}]
#set_input_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0] -max -add_delay 1.000 [get_ports {dnn_out_1_p[0]}]
#set_input_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0] -min -add_delay 0.100 [get_ports {scan_out_n[0]}]
#set_input_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0] -max -add_delay 1.000 [get_ports {scan_out_n[0]}]
#set_input_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0] -min -add_delay 0.100 [get_ports {scan_out_p[0]}]
#set_input_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0] -max -add_delay 1.000 [get_ports {scan_out_p[0]}]

create_clock -period 5.000 -name VIRTUAL_clk_inputs -waveform {0.000 2.500}
set_input_delay -clock [get_clocks VIRTUAL_clk_inputs] -min -add_delay 2.500 [get_ports -filter { NAME =~  "*scan_out_test*" && DIRECTION == "IN" }]
set_input_delay -clock [get_clocks VIRTUAL_clk_inputs] -max -add_delay 2.500 [get_ports -filter { NAME =~  "*scan_out_test*" && DIRECTION == "IN" }]
set_input_delay -clock [get_clocks VIRTUAL_clk_inputs] -min -add_delay 2.500 [get_ports -filter { NAME =~  "*config_out*" && DIRECTION == "IN" }]
set_input_delay -clock [get_clocks VIRTUAL_clk_inputs] -max -add_delay 2.500 [get_ports -filter { NAME =~  "*config_out*" && DIRECTION == "IN" }]
set_input_delay -clock [get_clocks VIRTUAL_clk_inputs] -min -add_delay 2.500 [get_ports -filter { NAME =~  "*dnn_out*" && DIRECTION == "IN" }]
set_input_delay -clock [get_clocks VIRTUAL_clk_inputs] -max -add_delay 2.500 [get_ports -filter { NAME =~  "*dnn_out*" && DIRECTION == "IN" }]
set_input_delay -clock [get_clocks VIRTUAL_clk_inputs] -min -add_delay 2.500 [get_ports {scan_out_n[0]}]
set_input_delay -clock [get_clocks VIRTUAL_clk_inputs] -max -add_delay 2.500 [get_ports {scan_out_n[0]}]
set_input_delay -clock [get_clocks VIRTUAL_clk_inputs] -min -add_delay 2.500 [get_ports {scan_out_p[0]}]
set_input_delay -clock [get_clocks VIRTUAL_clk_inputs] -max -add_delay 2.500 [get_ports {scan_out_p[0]}]
#create_clock -period 2.500 -name VIRTUAL_clk_outputs -waveform {0.000 1.25}
#set_output_delay -clock [get_clocks VIRTUAL_clk_outputs] -min -add_delay -1.000 [get_ports {bxclk_ana_n[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_outputs] -max -add_delay  0.250 [get_ports {bxclk_ana_n[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_outputs] -min -add_delay -1.000 [get_ports {bxclk_ana_p[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_outputs] -max -add_delay  0.250 [get_ports {bxclk_ana_p[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_outputs] -min -add_delay -1.000 [get_ports {bxclk_n[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_outputs] -max -add_delay  0.250 [get_ports {bxclk_n[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_outputs] -min -add_delay -1.000 [get_ports {bxclk_p[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_outputs] -max -add_delay  0.250 [get_ports {bxclk_p[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -min -add_delay -1.250 [get_ports {config_clk_n[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -max -add_delay 1.250 [get_ports {config_clk_n[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -min -add_delay -1.250 [get_ports {config_clk_p[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -max -add_delay 1.250 [get_ports {config_clk_p[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -min -add_delay -1.250 [get_ports {config_in_n[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -max -add_delay 1.250 [get_ports {config_in_n[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -min -add_delay -1.250 [get_ports {config_in_p[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -max -add_delay 1.250 [get_ports {config_in_p[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -min -add_delay -1.250 [get_ports {config_load_n[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -max -add_delay 1.250 [get_ports {config_load_n[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -min -add_delay -1.250 [get_ports {config_load_p[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -max -add_delay 1.250 [get_ports {config_load_p[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -min -add_delay -1.250 [get_ports {reset_not_n[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -max -add_delay 1.250 [get_ports {reset_not_n[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -min -add_delay -1.250 [get_ports {reset_not_p[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -max -add_delay 1.250 [get_ports {reset_not_p[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -min -add_delay -1.250 [get_ports {scan_in_n[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -max -add_delay 1.250 [get_ports {scan_in_n[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -min -add_delay -1.250 [get_ports {scan_in_p[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -max -add_delay 1.250 [get_ports {scan_in_p[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -min -add_delay -1.250 [get_ports {scan_load_n[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -max -add_delay 1.250 [get_ports {scan_load_n[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -min -add_delay -1.250 [get_ports {scan_load_p[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -max -add_delay 1.250 [get_ports {scan_load_p[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -min -add_delay -1.250 [get_ports super_pixel_sel]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -max -add_delay 1.250 [get_ports super_pixel_sel]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -min -add_delay -1.250 [get_ports vin_test_trig_out]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -max -add_delay 1.250 [get_ports vin_test_trig_out]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -min -add_delay -1.250 [get_ports {vin_test_trig_out_n[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -max -add_delay 1.250 [get_ports {vin_test_trig_out_n[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -min -add_delay -1.250 [get_ports {vin_test_trig_out_p[0]}]
#set_output_delay -clock [get_clocks VIRTUAL_clk_out1_cms_pix_28_fw_top_bd_clk_wiz_0_0_1] -max -add_delay 1.250 [get_ports {vin_test_trig_out_p[0]}]
